version = "0.1.0"

[preferences]
username = "Captain Typebeard"
difficulty = "beginner"
sound_enabled = true
animations_enabled = true

[ui]
theme = "classic"
font_size = 14
show_wpm = true
show_accuracy = true
highlight_errors = true

[game]
physics_enabled = true
spring_constant = 0.800000011920929
damping = 0.20000000298023224
game_mode = "practice"
